"""AcitivityRecord and ObservationRecord tables

Revision ID: 02ada026232e
Revises: 575a251ebb61
Create Date: 2019-12-10 16:04:24.874736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ada026232e'
down_revision = '575a251ebb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('heart_rate', sa.Float(), nullable=True),
    sa.Column('distance_from_start', sa.Float(), nullable=True),
    sa.Column('activity_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_record_id'], ['activity_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_record')
    op.drop_table('activity_record')
    # ### end Alembic commands ###
