"""changing records

Revision ID: ebf266cd6946
Revises: ce6f39eb189c
Create Date: 2019-12-16 09:40:38.895998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf266cd6946'
down_revision = 'ce6f39eb189c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation_record')
    op.add_column('activity_record', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('activity_record', sa.Column('date_time', sa.String(length=40), nullable=True))
    op.add_column('activity_record', sa.Column('heart_rate', sa.Float(), nullable=True))
    op.add_column('activity_record', sa.Column('time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_record', 'time')
    op.drop_column('activity_record', 'heart_rate')
    op.drop_column('activity_record', 'date_time')
    op.drop_column('activity_record', 'category')
    op.create_table('observation_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('elevation', sa.FLOAT(), nullable=True),
    sa.Column('pace', sa.FLOAT(), nullable=True),
    sa.Column('heart_rate', sa.FLOAT(), nullable=True),
    sa.Column('distance_from_start', sa.FLOAT(), nullable=True),
    sa.Column('activity_record_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['activity_record_id'], ['activity_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
